### ISSUE TITLE
django 1.8.2 error

### ISSUE THREAD

**Issue by bradrice** [django-blog-zinnia/zinnia-wysiwyg-ckeditor#7]
I'm getting an error in the ckeditor/widget.html template. This doesn't seem to happen in django 1.8.

in template /Users/brad2/Sites/braddev/lib/python3.4/site-packages/django/contrib/admin/templates/admin/includes/fieldset.html, error at line 19
ckeditor/widget.html
9	            {% for field in line %}
10	                <div{% if not line.fields|length_is:'1' %} class="field-box{% if field.field.name %} field-{{ field.field.name }}{% endif %}{% if not field.is_readonly and field.errors %} errors{% endif %}{% if field.field.is_hidden %} hidden{% endif %}"{% elif field.is_checkbox %} class="checkbox-row"{% endif %}>
11	                    {% if not line.fields|length_is:'1' and not field.is_readonly %}{{ field.errors }}{% endif %}
12	                    {% if field.is_checkbox %}
13	                        {{ field.field }}{{ field.label_tag }}
14	                    {% else %}
15	                        {{ field.label_tag }}
16	                        {% if field.is_readonly %}
17	                            <p>{{ field.contents }}</p>
18	                        {% else %}
19	
                                  
      {{ field.field }}
      

      
20	                        {% endif %}
21	                    {% endif %}
22	                    {% if field.field.help_text %}
23	                        <p class="help">{{ field.field.help_text|safe }}</p>
24	                    {% endif %}
25	                </div>
26	            {% endfor %}
27	        </div>
28	    {% endfor %}
29	</fieldset>n template /Users/brad2/Sites/braddev/lib/python3.4/site-packages/django/contrib/admin/templates/admin/includes/fieldset.html, error at line 19
ckeditor/widget.html
9	            {% for field in line %}
10	                <div{% if not line.fields|length_is:'1' %} class="field-box{% if field.field.name %} field-{{ field.field.name }}{% endif %}{% if not field.is_readonly and field.errors %} errors{% endif %}{% if field.field.is_hidden %} hidden{% endif %}"{% elif field.is_checkbox %} class="checkbox-row"{% endif %}>
11	                    {% if not line.fields|length_is:'1' and not field.is_readonly %}{{ field.errors }}{% endif %}
12	                    {% if field.is_checkbox %}
13	                        {{ field.field }}{{ field.label_tag }}
14	                    {% else %}
15	                        {{ field.label_tag }}
16	                        {% if field.is_readonly %}
17	                            <p>{{ field.contents }}</p>
18	                        {% else %}
19	
                                  
      {{ field.field }}
      

      
20	                        {% endif %}
21	                    {% endif %}
22	                    {% if field.field.help_text %}
23	                        <p class="help">{{ field.field.help_text|safe }}</p>
24	                    {% endif %}
25	                </div>
26	            {% endfor %}
27	        </div>
28	    {% endfor %}
29	</fieldset>

**Comment by ZachLiuGIS** [comment]
I'm using 1.8.2 and I got similar errors.

**Comment by Fantomas42** [comment]
Using django 1.8.4, and everythings works fine !

I close the issue until more informations.

**Comment by darbula** [comment]
Same issue, you need to add `'ckeditor'` to `INSTALLED_APPS` to work, this is noted in README:

> Install and configure django-ckeditor if not already done.
